development:
  adapter: postgresql
  encoding: unicode
  database: policy_development
  pool: 5
  host: localhost
  username: postgres
  password: gado595

production:
  adapter: postgresql
  encoding: unicode
  database: policy_production
  pool: 5
  host: localhost
  username: postgres
  password: gado595

